### ISSUE TITLE
Windows binaries 32-bit/ 64-bit (POPCNT, AVX, but no BMI2.exe)

### ISSUE THREAD

**Issue by ChessGUI** [justinaustin/ruci#3]
Can you please build Windows binaries 32-bit/ 64-bit  of the source code and host these files on GitHub, too (e.g. subdirectory /releases) ?

**Comment by justinaustin** [comment]
As the codes sits right now, I don't feel comfortable distributing binaries (as the project isn't release ready). However, I definitely will be sure to include Windows binaries when the time comes. Thanks!
